server:
  port: 9001


eureka:
  client:
    serviceUrl:
      defaultZone: http://872509-eureka-lb-916980668.us-east-1.elb.amazonaws.com/eureka/


spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: authorization-service
  datasource:
    url: jdbc:h2:mem:usersDb
    platform: h2
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
      
